### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by krak3n77** [m1ch3al/flipper-zero-rogue-master-firmware#1]
Have you seen the fbt github action?

**Comment by m1ch3al** [comment]
Hi detectingdragon77, no...I didn't hear anything about that.
Can you explain to me ? Did you have some links/material to read ?

Thank you !!

**Comment by krak3n77** [comment]
> Hi detectingdragon77, no...I didn't hear anything about that. Can you explain to me ? Did you have some links/material to read ?
> 
> Thank you !!

https://github.com/oleksiikutuzov/flipperzero-ufbt-action
Heres the repo, honestly i have never used it, I have always compiled using my computer.

**Comment by m1ch3al** [comment]
Thank you detectingdragon77 !
I will give a try to understand what we can integrate ! 
**Thank you in advance for the suggestion, I appreciate a lot !**
