### ISSUE TITLE
Empty Zip files

### ISSUE THREAD

**Issue by jamine16** [m1ch3al/flipper-zero-rogue-master-firmware#2]
The last 3 or 4 Zip files have been empty.

**Comment by m1ch3al** [comment]
Thank you for advise me. I've an automatic chain that compile and publish the zip.
I'm just checking ...

Thank you so much !!!

**Comment by m1ch3al** [comment]
Hi [jamine16](https://github.com/jamine16), now it seems to be fixed...there was an application that didn't compile.
Thank you for you patience !!
